### ISSUE TITLE
Future Feature Request:  Add a shutdown or pseudo shutdown command.

### ISSUE THREAD

**Issue by JonMurphy** [boblemaire/IoTaWatt#104]
It seems like the iotawatt is writing lots of data to the SD card.  So powering down the iotawatt could cause a file corruption or a SD card corruption.

From digging thru the ESP docs I didn't find a shutdown command (but I could be blind!).  So I am hoping a pseudo shutdown command could be created by turning off abilities to write to the SD card, turn off interrupts (if used), and putting the iotawatt into a continue loop or to sleep until powered down.

**Comment by boblemaire** [comment]
In reality, IoTaWatt writes to the SD card once every 5 seconds, and to the extent possible, precautions to minimize the probability of file corruption have been taken.  Also, the data log as now has a low resolution (2 min) backup in the history log.

The latest release has a software restart to eliminate power cycle type restarts.  So this change would not do anything to mitigate the only remaining exposure to potential SD card corruption, which is unanticipated power failure.
