### ISSUE TITLE
Send values to USB

### ISSUE THREAD

**Issue by iBobik** [boblemaire/IoTaWatt#115]
In my project I want to power IotaWatt from a computer (Turris Omnia or RaspberryPi) and use values in [Home Assistant](https://home-assistant.io) (can receive values from any /dev/tty*).

Is it possible to configure IotaWatt to also send all values over USB? (And optionally disable all radio?)

**Comment by boblemaire** [comment]
Negative.  The serial output is currently used as a diagnostic output, and there is no mechanism to send a data stream as well.  That said, It would be possible to modify the code to start up a Service that squirts data out on the serial port.  The data would be intermingled with any diagnostic output, but a protocol could be defined to identify the data.

Unfortunately, that's not consistent with the design of the primary software and I'm not interested in doing that or merging anything like that into the current code.  You are welcome to make your own fork and go to it.
