### ISSUE TITLE
add check for Name field

### ISSUE THREAD

**Issue by JonMurphy** [boblemaire/IoTaWatt#119]
add check for Name field.  Should only be a number.

Setup > Web Server > Edit 

<img width="306" alt="screen shot 2018-01-17 at 10 45 20 am" src="https://user-images.githubusercontent.com/15616372/35055100-ed56a55e-fb73-11e7-86a1-56ec7b9dde2c.png">

**Comment by boblemaire** [comment]
Fixed in release 02_02_29.  Thanks.
