### ISSUE TITLE
own compile - no VT active

### ISSUE THREAD

**Issue by promy** [boblemaire/IoTaWatt#127]
I tried to compile and flash this version (with and without the changed samplePower.cpp - version 02-02-29 dd 25/01/2018)
Ran ok, but, it didn't capture the VT's (and as such no power measurements on the CT's i guess), everything stayed on 0. I changed the sd files (all exept the config) but no luck.

Reflashed back to an old version (02-02-26) i had downloaded (and running on another IotaWatt), and this version worked OK (changed the sd files back since with the new sd files this version showed a wrong "ac cycles sampled/second) (5 vs 28)

**Comment by boblemaire** [comment]
Not much to go on here.  Not sure what "this" version means when it is "with and without" one of the components.  All I can say is that the released version 02_02_29 is at auto-update MINOR and running without incident.  Can you download and run the firmware binary for 02_02_29?

**Comment by boblemaire** [comment]
No further information after 2 weeks, closing this as insufficient information to reproduce.
