### ISSUE TITLE
emoncms on https not working

### ISSUE THREAD

**Issue by dtony** [boblemaire/IoTaWatt#128]
I tried to configure IoTaWatt using my own emoncms instance hosted with a valid (Let's Encrypt) SSL certificate but it fail. I have a redirection on my apache reverse proxy to redirect http to https. I could read in the logs :
`2/5/18 13:29:40 EmonService: started.url: emon.mydomain.com:443/emoncms, node: IotaWatt, post interval: 10, unsecure GET`
`2/5/18 13:29:40 EmonService: input/get failed.`
I tried different format for the url :
- https://emon.mydomain.com/emoncms
- https://emon.mydomain.com/emoncms/
- https://emon.mydomain.com:443/emoncms
- https://emon.mydomain.com:443/emoncms
- emon.mydomain.com:443/emoncms

I finally remove the redirection and served emoncms on port 80 with http and then it worked :
`2/5/18 13:42:23 EmonService: started.url: emon.mydomain.com:80/emoncms/, node: IotaWatt, post interval: 10, unsecure GET`
`2/5/18 13:42:23 EmonService: Start posting at 1517834540`

**Comment by boblemaire** [comment]
The message doesn't provide a lot of information about the cause of the failure, and that's not always informative anyway.  The "input/get failed" is the initial transaction issued by Emonservice to obtain the time of the last input to Emoncms.  Posting will resume from that point.  That transaction is not secure (although the apikey is somewhat obfuscated in base-64 in a HTTP header).  Once that transaction completes, subsequent data posting can be done using the secure Emoncms post protocol that encrypts the payload.  Not sure of the status rolling that out to the local Emoncms code.

At this point, the only other option I can offer is to use a different port.  You can append a :port to the Emoncms URL during configuration and have your instance serve HTTP on that port.

Currently working on using asyncTCP in IoTaWatt.  There is a lightweight TLS option available there that I intend to explore.  If it can run reliably in the heap available, I will consider supporting HTTPS directly from IoTaWatt.  It's a long shot.  Beyond that, the ESP32 should offer sufficient resources in the future.
