### ISSUE TITLE
Allow negative power value unchecked seems to take effect only after reboot

### ISSUE THREAD

**Issue by daniwebCH** [boblemaire/IoTaWatt#165]
version 02_03_07 
Procedure:
1) change of parameter "Allow negative power value" from selected to not selected from an input
2) In status the view the value is still shown as negative
3) Reboot IoTaWatt
4) Now on status the value is correctly shown

PS: On the other direction (seems to be ok without reboot)

**Comment by boblemaire** [comment]
Thanks,
Fixed in development branch.  Should merge to next release.

**Comment by boblemaire** [comment]
Fix released in 02_03_08.
