### ISSUE TITLE
IotaWatt - damaged config - restore /SD?

### ISSUE THREAD

**Issue by bluetardis** [boblemaire/IoTaWatt#168]
Hi - I have an iota watt that want boot - config seems not to be correct.    Can I use use the contents of /SD and restore this over the SD card in the device to get things working?

**Comment by boblemaire** [comment]
Probably.  It depends what release you are on.  The SD directory in the master branch matches the current release.  Give it a try.  If still problems, look up your release in this Repo and extract the SD directory for your release there.

The [IoTaWatt forum](https://community.iotawatt.com/latest) is the best place to get support with problems like this.  The tools for sharing diagnostic information are better and it is more closely monitored.
