### ISSUE TITLE
Design documentation

### ISSUE THREAD

**Issue by ptr727** [boblemaire/IoTaWatt#171]
Hi, could you please produce, post, or point me to your design documentation?
E.g. design reasoning, component selection reasoning, component value calculation, etc.

Something like this:
https://www.switchcraft.org/project-blog/2016/12/11/designing-a-voltage-sensing-pcb

Thank you

**Comment by boblemaire** [comment]
There is no such documentation.  All of the documentation, such as it is, is contained in this Repo.  Thanks for your interest.
