### ISSUE TITLE
Can´t flash .bin on new NodeMcu (same model of project)

### ISSUE THREAD

**Issue by Renatotheo** [boblemaire/IoTaWatt#206]
Hello,

i´m trying to flash .bin ( IoTaWatt-02_03_21) on new NodeMCU (same model of the project) , but i can´t see SSDI like original project , just default SSID of Node, and can´t connect in ID:192.168.4.1, i don´t know if i´m using correct tool ( NodeMcu pyFlasher).

Thank you

**Comment by boblemaire** [comment]
Hello @Renatotheo ,
This isn't the proper place to solicit help with using the ESP8266.  The [IoTaWatt forum](https://community.iotawatt.com/latest) has a DIY thread where someone may respond to a question like this.  I would recommend that you use platform I/O to compile and upload firmware.  If you are just trying to load a firmware from one of the releases, esptool.py is my weapon of choice.
