### ISSUE TITLE
Output frequency to webserver

### ISSUE THREAD

**Issue by DTFUHF** [boblemaire/IoTaWatt#211]
Although line frequency is not logged (#121) it would be nice to be able to output this to InfluxDB.

**Comment by boblemaire** [comment]
You can do that.  Define a measurement that is a voltage input and specify units Hz. 

These issues are better raised in the forum at [https://community.iotawatt.com/](https://community.iotawatt.com/)

**Comment by DTFUHF** [comment]
Thanks, I did not know that existed.
