### ISSUE TITLE
Sensors failing or device failing?

### ISSUE THREAD

**Issue by rotcop4u2** [boblemaire/IoTaWatt#231]
I have had the Iotawatt for almost 10 months now, and I'd have to say I love it. But over the past few months I have noticed that the sensors seem to dropping value. I bought a full US kit with ECS1050 sensors. The reason I know the values are dropping is because I could go from 800 watts on one sensor to 200 the next day, when I know the usage of that circuit is only fluctuating from 400 to 800 because of a usage meter that I have installed from my solar company. Are there any suggestions on why? Or is it possible to get replacement sensors?

**Comment by boblemaire** [comment]
This isn't an issue with IoTaWatt firmware.  You can get support for the hardware on the forum at [https://community.iotawatt.com/](https://community.iotawatt.com/).
