### ISSUE TITLE
Coding style nit: use boolean OR, not bitwise OR

### ISSUE THREAD

**Issue by jtbattle** [boblemaire/IoTaWatt#242]
I don't have a device and am not working on this code, but I was poking around here because I was thinking about getting a system (95% sure).  Anyway, I noticed this recent change in CSVquery.cpp, line 284:

     if(method.length() != 2 | method[1] < '0' | method[1] > '9') return false;

Those bitwise ORs should really be boolean ORs.  It won't make a functional difference, of course, but conceptually it would be better.

**Comment by boblemaire** [comment]
While conceptually the same, this would be better functionally if submitted as a PR.
