### ISSUE TITLE
Lost connection to influxdb since 20th April

### ISSUE THREAD

**Issue by Antibrumm** [boblemaire/IoTaWatt#270]
Hi
I just realized that since the 20th April both my Iotawatts stopped transmitting their data to my InfluxDB instance. Watching the logs it seems that the Last Entry Query results into a 404 Page not found. Might it be linked to the update 02_05_07 or 02_05_06?

My InfluxDB version is 1.7.9 (which did not change).

I'm not sure the logs are really helpful, but here it is:

SD initialized.
4/20/20 20:02:43z Real Time Clock is running. Unix time 1587412963 
4/20/20 20:02:43z Reset reason: Software/System restart
4/20/20 20:02:43z Trace:  9:3, 9:5, 9:9, 1:2, 1:3, 1:4, 1:5[7], 7:0, 7:7, 1:6, 1:3, 1:4, 1:5[19], 1:6, 1:1[8], 1:2[9], 9:0[9], 9:0, 9:1, 8:4, 8:6, 8:8, 8:9, 9:3, 9:5, 9:9, 1:2, 1:3, 1:4, 1:5[5], 5:0, 5:7
4/20/20 20:02:43z ESP8266 ChipID: 6147826
4/20/20 20:02:43z IoTaWatt 5.0, Firmware version 02_05_07
4/20/20 20:02:43z Updater: Installing update files for version 02_05_07
4/20/20 20:02:43z Updater: Installing EDIT.HTM
4/20/20 20:02:43z Updater: Installing GRAPH.HTM
4/20/20 20:02:43z Updater: Installing GRAPH.JS
4/20/20 20:02:43z Updater: Installing GRAPH2.HTM
4/20/20 20:02:44z Updater: Installing GRAPH2.JS
4/20/20 20:02:44z Updater: Installing INDEX.HTM
4/20/20 20:02:45z Updater: Installing TABLES.TXT
4/20/20 20:02:45z Updater: Installing CNFSTYLE.CSS
4/20/20 20:02:45z Updater: Installation complete.
4/20/20 20:02:45z SPIFFS mounted.
4/20/20 23:02:46 Local time zone: +2:00
4/20/20 23:02:46 Using Daylight Saving Time (BST) when in effect.
4/20/20 23:02:46 device name: Iota2
4/20/20 23:02:46 HTTP server started
4/20/20 23:02:46 timeSync: service started.
4/20/20 23:02:46 statService: started.
4/20/20 23:02:46 dataLog: service started.
4/20/20 23:02:47 dataLog: Last log entry 04/20/20 23:02:15
4/20/20 23:02:47 historyLog: service started.
4/20/20 23:02:47 historyLog: Last log entry 04/20/20 23:02:00
4/20/20 23:02:50 WiFi connected. SSID=SOMEID, IP=192.168.1.150, channel=7, RSSI -72db
4/20/20 23:02:50 MDNS responder started for hostname Iota2
4/20/20 23:02:50 LLMNR responder started for hostname Iota2
4/20/20 23:02:50 Updater: service started. Auto-update class is MINOR
4/20/20 23:02:51 influxDB: started, url=HTTP://diskstation.local:8086/, db=iotawatt, interval=10
4/20/20 23:02:51 Updater: Auto-update is current for class MINOR.
4/20/20 23:02:51 influxDB: Last entry query failed.
4/20/20 23:02:51 influxDB: HTTPcode 404, 404 page not found

Let me know if i can help with anything :)

Thanks
Martin

**Comment by boblemaire** [comment]
Hi Martin,
I have to wonder how diskstation.local gets resolved.  I am unaware of IoTaWatt doing anything to resolve outbound addressing like that.  Maybe it did on 02_05_02 and prior with the old core and lwip 1, but with 02_05_07 (and you should now be upgraded to 02_05_08) there is a new core with a new lwip 2.  I suspect that may have something to do with it.  Can you try using the diskstation IP address instead?  If that fails, please post this issue on the [forum](https://community.iotawatt.com/latest).  You can see that I didn't notice this for 4 days.  Response time on the forum is measured in hours.  Also, the forum is much easier to post information and leaves a trail for others who may have the same problem.

I'm going to close this github issue.
