### ISSUE TITLE
registration on community.iotawatt.com would not work if via http

### ISSUE THREAD

**Issue by yarikoptic** [boblemaire/IoTaWatt#271]
wasn't sure where to report... so here it is FYI: if you try to register while accessing via http:// -- it would complain that cannot set cookie.  Accessing via https seems proceeded (expecting confirmation email to arrive)

**Comment by boblemaire** [comment]
I don't get involved in the administration of the forum site.  It's a service that I buy and is hosted by the provider.  The softwaqe is discourse, which is open source and [available here on Github](https://github.com/discourse/discourse). I wouldn't want to be in the middle of reporting this as a problem, but feel free to file an issue with the discourse folks.
