### ISSUE TITLE
Is it possible to use this front end with different use case with modification?

### ISSUE THREAD

**Issue by happytm** [boblemaire/IoTaWatt#273]
This is perfect front end for it's intended use case of energy monitor.

Is it possible to use this front end with different use case with modification? 

Can those 14 input values in your code be replaced by 14 sensor values with modification ?

I wanted to use it with a ESP8266 based multi sensor device which will output about 5 different sensor values like voltage, temperature, humidity & pressure (using BME280) and light sensor etc  and 6 different status values for that device for home automation.  I would like to collect all these sensor data every few minutes which can be displayed later on in graph or table format. My main goal is to keep data local so I do not have to rely on cloud or internet. Right now my code for multi sensor gateway device put out sensor data via MQTT in following format under 2 main topics:

deviceStatus/{"location":"Livingroom","rssi":"-68","mode":"0","ip":"6","channel":"7","sleeptime":"1","uptime":"140"}

sensorValues/{"location":"Livingroom","voltage":"2.62","temperature":"1","humidity":"2","pressure":"147","light":"82"}

deviceStatus/{"location":"Bedroom1","rssi":"-69","mode":"0","ip":"26","channel":"7","sleeptime":"1","uptime":"209"}

sensorValues/{"location":"Bedroom1","voltage":"2.62","level":"8","presence":"0","motion":"29","custom":"40"}

deviceStatus/{"location":"Kitchen","rssi":"-52","mode":"0","ip":"16","channel":"7","sleeptime":"1","uptime":"145"}

sensorValues/{"location":"Kitchen","voltage":"2.62","level":"0","presence":"0","motion":"0","custom":"0"}

Please guide me.

Thanks.

**Comment by boblemaire** [comment]
From the beginning it was conceived that other metrics might be collected, and some of the ones that you mention.  I definitely think it's possible to do, but there are limitations:

- 
- Adding other types of inputs requires that the hardware support the sensors.  The ESP8266 does not have a lot of GPIO pins.  There are no unused pins in the current device.  The pins used for SPI also serve the SDcard, so can't eliminate that.  The I2C also services the RTC, so can't eliminate that.  There are the CS pins for the ADCs if you want to abandon power sampling, and the single ESP8266 ADC is also available.
- 
- Adding different sensor types would require a rethinking of the UI and how to configure.
- 
- MQTT support would need to be added, which is puts pressure on available HEAP.  Another option is to use a HTTP agent to send the MQTT.

If you decide to do this, and want to have a portal to ask questions, please use the "Homebrew" category  in the [iotawatt forum](https://community.iotawatt.com/).

**Comment by happytm** [comment]
Thanks for your detailed response. I agree there is limitation regarding available gpio pins. I was planning to use  BME280 sensor for Temperaure, Humidity and Pressure and use either APDS-9960 for light or gesture sensor. I was planning to use Arduino Pro Mini as a I2C slave to extend the gpio pins. If ever you decide to implement this framework for ESP32 please consider other use cases. this is very beautiful front end and could be very flexible for other use cases.

Thank anyways for your help.
