### ISSUE TITLE
Add button to graph+ to return to main screen

### ISSUE THREAD

**Issue by jlquinn** [boblemaire/IoTaWatt#278]
Hi and thanks for all your work.
Please consider adding a button to the graph+ page that navigates back to the main screen.  I know I can do it with the back arrow/key shortcut, but it's convenient to have it clickable.
8/30/20 20:14:24z IoTaWatt 5.0, Firmware version 02_05_09

**Comment by boblemaire** [comment]
This belongs in the PR section.
