### ISSUE TITLE
Show status by default on visiting main page

### ISSUE THREAD

**Issue by jlquinn** [boblemaire/IoTaWatt#279]
Feature Request

When I first visit the iotawatt.local page, I see the 4 buttons with no other info.  Please consider showing status by default.  If the unit hasn't been configured yet, perhaps show a message that says it's waiting for you to set up inputs, etc.

One way this happens is if I go the graph+ page, then use the back arrow, the status folds up and I only see the 4 buttons.

8/30/20 20:14:24z IoTaWatt 5.0, Firmware version 02_05_09
Browser Firefox 80 on Ubuntu 18.04

**Comment by boblemaire** [comment]
That's more complicated than it sounds.  The status display has many tabs.  There's a default set that is used, but starting up with that displayed just begs another request to be able to set the defaults.  What would be more useful IMO, would be an app that displays a configurable dashboard of inputs and outputs.  Something like that  could be offered from the main Data button, and like Graph+, have the ability to be launched independently  and imbedded.

I'm going to close this issue out.  It would be nice to see it resurface as a PR from an industrious user.
