### ISSUE TITLE
Tiny typo on the home page

### ISSUE THREAD

**Issue by amosshapira** [boblemaire/IoTaWatt#301]
A tiny typo on the home page, an unnecessary apostrophe:

> With it's integrated web-server you can manage setup

Should be `its` instead.

EDIT: I see this mistake in other places on that page.

**Comment by boblemaire** [comment]
This is an open project. Always looking for folks with other skills like proofreading. This is an open project. The documentation can be forked, edited and a pull request created.

**Comment by amosshapira** [comment]
I tried to find which file should be edited to create a PR but couldn't find it.
