### ISSUE TITLE
Add CT - SCT-016 

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [boblemaire/IoTaWatt#316]
https://github.com/boblemaire/IoTaWatt/blob/master/SD/tables.txt

https://pdf1.alldatasheet.com/datasheet-pdf/view/1159368/YHDC/SCT016.html

No idea what to add for phase- but, its 3,000 turns. 

{"model":"SCT016","mfg":"YHDC","type":"C","turns":3000,"phase":0},

**Comment by boblemaire** [comment]
This looks suspiciously like the CR3110, and probably is the same thing.  The process for adding CTs to the tables is to contact me (@overeasy) on the forum.  I have equipment to test the phase shift and will need two samples of the new CT to test and retain. 

Note that the datasheet specifies a maximum ballast resistance of 10 Ohms, but the VA chart goes up to 1K.  IoTaWatt uses 20 Ohm, and I don't think it will be a problem. FWIW I think the SCT013-000 is a better choice in this range.
