### ISSUE TITLE
Firmware builds

### ISSUE THREAD

**Issue by Onepamopa** [boblemaire/IoTaWatt#332]
Hello,

Why isn't there a newer build of the firmware? The device runs 02_07_05 (Dec 17, 2021), there are plenty of commits since then.

**Comment by boblemaire** [comment]
There are issues with incorporating the latest ESP/Arduino core.  It is still risky to release to the installed base. I am working it from both ends.  Hoping for a core update and testing workaround code.  You are welcome to try the current master and report back an issues or lack thereof on the forum.
