### ISSUE TITLE
upgrading firmware on device with no internet access

### ISSUE THREAD

**Issue by craftyguy** [boblemaire/IoTaWatt#334]
for various reasons, I have my iotawatt on a network that is completely isolated from the internet, so the firmware update mechanism that fetches/flashes firmware updates obviously doesn't work. is there a way to push firmware to it without giving it access to the internet? I'm able to connect a laptop to the same wifi network it is on, I just didn't see any obvious way to upload any updates, either through the web UI or some other API.

**Comment by boblemaire** [comment]
The firmware release packet is at [https://iotawatt.com/firmware/bin/02_07_05.bin](https://iotawatt.com/firmware/bin/02_07_05.bin)
