### ISSUE TITLE
Graph+ last 3 hours and last 6 hours has error

### ISSUE THREAD

**Issue by chriszylstra** [boblemaire/IoTaWatt#339]
Hi there,

I'm getting this request error message I try to select last 3 hours or last 6 hours. 
Note: I do not actually have full data for 3 hours ago as I just installed my IoTaWatt. I am just mentioning this because the error does not appear on any other timeframe that I do not have data for yet. (such as last 24 hours). Because of these errors, the graph will not plot even the partial data which I have on the 3 hours or 6 hours timeframe.

I will wait 6 hours and update this if the issue is still happening or has gone away. It might just be an edge case error of the first 6 hours after installing the device. 

Thanks, 
-cz

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/13257196/215279308-50ddfd7a-7a5f-4089-8aeb-8951121dc81c.png">

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/13257196/215279383-47697651-a9ea-4e6f-9111-9b1969fc51e0.png">

**Comment by chriszylstra** [comment]
Update: Error goes away when there is more than 6 hours of data. So maybe its a non-issue, just letting you know the details.

**Comment by boblemaire** [comment]
I'm aware of this issue.  There is a fix in the ESP32 code that needs to be applied to the ESP8266.  But seeing it is an edge issue, doesn't warrant a release.
