### ISSUE TITLE
After update stuck in reboot loop 

### ISSUE THREAD

**Issue by ramiws** [boblemaire/IoTaWatt#344]
Hi 

I updated to  02_08_02 and then got into this loop of reboot "file damaged ". One time it worked but then went crazy again on loop for "low sample count". Then I reboot and got stuck at "file damaged " loop again. I copied SD content from github repo to sd card, I thought that this new version needs that, but no luck 

`

SD initialized.
4/11/23 15:45:10z Real Time Clock is running. Unix time 1681227910 
4/11/23 15:45:10z Reset reason: Exception
4/11/23 15:45:10z Trace:  1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:1[1], 1:2, 9:0, 9:0, 8:3, 8:3, 1:3, 1:3, 1:3, 1:3, 1:3, 1:3
4/11/23 15:45:10z ESP8266 ID: 6308290, RTC PCF8523 (68)
4/11/23 15:45:10z IoTaWatt 4.x, Firmware version 02_08_02
4/11/23 15:45:10z SPIFFS mounted.
4/11/23 15:45:10z Local time zone: +0:00
4/11/23 15:45:10z device name: IotaWatt
4/11/23 15:45:10z HTTP server started
4/11/23 15:45:10z timeSync: service started.
4/11/23 15:45:10z statService: started.
4/11/23 15:45:10z dataLog: service started.
4/11/23 15:45:10z IotaLog: file damaged /iotawatt/iotalog.log

4/11/23 15:45:10z IotaLog: Creating diagnostic file.
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
0,0,0,0
4/11/23 15:45:10z IotaLog: Deleting /iotawatt/iotalog.log and restarting.

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v0008e1b0
~ld
␄�oN�␀�no�쒃�`␃␡�␛␒␌�no�쒃� ␃␡�␛"␌�Nn��|␛�� ␂�"$`␂r�o␏lph��␃�␓�o�|␛r��N|�␌$␌�␄l ␂␜#�␓␂␄��␒r�␂l�N�␌�N�␀␌$`␂��{�l�$␛�
SPI started.

** Restart **

`

**Comment by boblemaire** [comment]
This is an issue for the forum. It is probably related to the defective SDcard debacle.
