### ISSUE TITLE
compact DIN version

### ISSUE THREAD

**Issue by gkasprow** [boblemaire/IoTaWatt#345]
I purchased 3 original IoTaWatt units to monitor all my circuits and hardly managed to fit them into my cabinet. The audio jacks and 3 VTs took so much space. It's standard situation in Europe.
![2023-07-09 18 38 18](https://github.com/boblemaire/IoTaWatt/assets/4325054/6630b253-8928-43ef-9149-8d947f2b5d21)
I need to add a few more DIN rail devices, i.e. individual RCBs so had to optimise the energy monitoring dimensions.
So, I designed compact 3-phase version with embedded voltage transformers and power supply.
I also discovered that in my device the LM358 with 10uF load is oscillating so I fixed that issue by adding compensation network.
![image](https://github.com/boblemaire/IoTaWatt/assets/4325054/b2c8d83e-a38b-48a3-9e58-120605d9b577)
I also used miniature CTs from Talema (AZ-1000) with embedded resistors.
The design is in Altium but one can easily convert it to Kicad when necessary.
![image](https://github.com/boblemaire/IoTaWatt/assets/4325054/7179d7f7-628c-4693-be81-248394217bed)

The PCB fits nicely low cost D6MG enclosure from GAINTA. No cutouts are needed.
The image shows enclosure with front panel removed.
![image](https://github.com/boblemaire/IoTaWatt/assets/4325054/8d319301-45c7-4f53-97ba-73f7566463aa)

The schematic and production files are [here](https://github.com/gkasprow/IoTaWatt_DIN/releases/tag/v1.0rc1)

The sources are [here](https://github.com/gkasprow/IoTaWatt_DIN)

I'm not sure about licensing model. I usually release all my designs using CERN OHL, can you guide me what license shall I use?
Do you think I can use IoTaWatt_DIN name for my design?
I think you should add this version to your offer, Europe will love it.

**Comment by 6fta** [comment]
I also started to make a pcb for the rail from ZMPT107-1 transformers, but due to lack of time I did not complete the project.
![IotaWatt-poiect](https://github.com/boblemaire/IoTaWatt/assets/46684864/2354d3d3-b99e-49d5-acb4-ef949d721260)

**Comment by gkasprow** [comment]
I see you added anti-aliasing capacitors at the inputs ?

**Comment by 6fta** [comment]
Capacitors are optional, I took into account the article in the following link. [ Low current measurement performance of the SCT013](https://www.casler.org/wordpress/low-current-measurement-performance-of-the-sct013/)

**Comment by gkasprow** [comment]
I think they are the must. To properly measure signals, one must meet the Nyquist criterium of sampling. For the moment the bandwidth is limited only by CT and VT. For pure sine is fine, but we have broad spectrum of interferences in mains.

**Comment by gkasprow** [comment]
One more think. The ADC when sampling, is charging internal capacitor. So it needs low driving impedance. Usually one uses opamp or RC filter where C serves as a reservoir of charge for sampling. In case of CTs, that's not a problem. The VTs have 1k of resistance and this causes measurement error (systematic). Adding 1nF will do two things - limit the BW and meet Nyquist criteria and provide low impedance for ADC.

**Comment by gkasprow** [comment]
I meant harmonics and EM interferences generated by loads running on frequencies higher than mains, for example, brushed motors, DC/DC converters etc.

**Comment by perigoso** [comment]
Here I was thinking about designing a compact DIN rail version, because my cabinet is quite tight...
Good work @gkasprow! I might fabricate one of yours, have you encountered any issues (that I should try to fix before making my own)?

**Comment by gkasprow** [comment]
Somebody built it and so far there is only one non-critical issue
https://github.com/gkasprow/IoTaWatt_DIN/issues/1
I still didn't find time to assemble my PCBs. Existing IotaWatt is working well.  Perfect is the enemy of good
