### ISSUE TITLE
Add SCT006-000

### ISSUE THREAD

**Issue by glynhudson** [boblemaire/IoTaWatt#76]
Would it be possible to add SCT006-000 to the Iotawat CT list, currently SCT013 and SCT019 are listed but not yet SCT006

![iotawatt configuration app - google chrome_117](https://user-images.githubusercontent.com/758844/31348529-e388fd74-ad17-11e7-912e-ca0709e0318a.png)

Here's a comparison table 

![ecd36d35dee281f270c60517ca4c1a10926c6481](https://user-images.githubusercontent.com/758844/31348508-d1cbfa32-ad17-11e7-8d33-70083e5f4b6c.png)

**Comment by boblemaire** [comment]
I just checked and it's in the master branch.  Can you verify?

**Comment by glynhudson** [comment]
Yes, I can confirm. Thanks 👍 

I've just made a minor change to enter the full name of SCT006 > SCT006-000 to avoid any confusion and keep consistency with the other CT's. This change has been included in my PR https://github.com/boblemaire/IoTaWatt/pull/77 

https://github.com/boblemaire/IoTaWatt/pull/77/commits/9a6d381b335c2a790f462a6fbffe729b4263d77f

**Comment by boblemaire** [comment]
PR #77 merged

**Comment by fredrike** [comment]
I've got a couple of SCT006 that is rated 20A: 25mA which corresponds to: http://en.yhdc.com/product/SCT006-612.html 

Will the SCT006-000 work ok or should I use a generic one (seems to be 1:800 turns on my version too)?

**Comment by boblemaire** [comment]
That looks like the same one I tested.   You should be able to configure with the standard SCT006-000 menu pick.
