### ISSUE TITLE
Print local IP address to serial 

### ISSUE THREAD

**Issue by glynhudson** [boblemaire/IoTaWatt#78]
Hostname resolution e.g http://iotawatt.local does not work on my office network. It would be very useful if IotaWatt printed it's local IP address to serial on setup

**Comment by boblemaire** [comment]
Added to connect message.  Will appear in message log as well as on Serial console if connected.  It's still a catch-22 if you don't have a serial connection.  The .local address is mDNS.  There are several multiple implementations available.  Installing Apple's Bonjour should work.
