### ISSUE TITLE
Web interface for channel configuration does not work in Edge or IE

### ISSUE THREAD

**Issue by Frogmore42** [boblemaire/IoTaWatt#89]
Configure Inputs screen does not allow selection of CT.  It appears events are continually getting fired and the JavaScript does not deal with that well.  This also causes the browser to use a lot of CPU (on the PC) and makes it seem like the IotaWatt is dead.

Simple solution is to use Chrome which does appear to work okay.

**Comment by boblemaire** [comment]
Firefox works fine as well.  I have avoided Edge because I don’t use it in general, but Specifically because I couldn’t figure out how to specify the mDNS (.local) address.  Didn’t research it thoroughly.  I’ll revisit.

**Comment by boblemaire** [comment]
Fixed in release 02_02_24.  Either adopt that release via auto update class alpha, or just download SD/index.htm from the master branch to your iotawatt SD.
