### ISSUE TITLE
Question:  U$3  VREF_SHUNT model

### ISSUE THREAD

**Issue by skabashnyuk** [boblemaire/IoTaWatt#94]
Could you please identify the model of this shunt?
Is this https://octopart.com/search?q=ADR5045A ? Voltage 5.0?

**Comment by boblemaire** [comment]
I'm currently using TL4050B25IDBZR (Texas Instruments).  That said any SOT-23-3 shunt with a voltage less than 3.2V will work.  The over all accuracy of the device is based on this component, so I use a 0.2% tolerance.  Whatever you use, the default voltage in the software is 2.5V but that can be changed, either in the software or specified in the configuration file.
