### ISSUE TITLE
Component Quality

### ISSUE THREAD

**Issue by Roo-2** [boblemaire/IoTaWatt#96]
#94 
> The over all accuracy of the device is based on this component, so I use a 0.2% tolerance.

Can you give sample part numbers for C0805 (1uf & 10uf) and R0805 (220R, 24R, 1K, 4.7K & 12K) packages?

What is quality of Chinese NodeMCU?

**Comment by boblemaire** [comment]
Resistors are mostly .5% 1/10watt.  Capacitors are garden variety.
What is quality of Chinese NodeMCU?  I am not aware of any metric or standard by which the relative quality of this open hardware commodity is measured.

**Comment by Roo-2** [comment]
[https://community.iotawatt.com/t/resistor-tolerance/23](url)
